language: cpp

before_install:
 - if [[ $CTP = yes ]]; then sudo add-apt-repository -y ppa:boost-latest/ppa; fi #newer boost for libboost_timer
 - sudo apt-get update
 - sudo apt-get install cmake libfftw3-dev libgsl0-dev txt2tags libboost-program-options-dev libboost-filesystem-dev libboost-system-dev libexpat1-dev libsqlite3-dev pkg-config mercurial
 - if [[ $MAN ]]; then sudo apt-get install pgf texlive-fonts-recommended texlive-latex-extra doxygen graphviz; fi
 - if [[ $TEST = *cma* ]]; then sudo apt-get install python-numpy gnuplot-nox; fi
 - if [[ $TEST = *imc ]]; then sudo apt-get install octave; fi
 - if [[ $TEST = *simplex* ]]; then sudo apt-get install gnuplot-nox; fi
 - if [[ $TEST = *realtime ]]; then sudo apt-get install gnuplot-nox; fi
 - if [[ $GROMACS != yes ]]; then sudo apt-get install gromacs-dev; fi
 - if [[ $CTP = yes ]]; then sudo apt-get install libboost1.48-all-dev; fi

env: #NINJA=1 is currently not support by Travis' cmake, enable when >=2.8.9
  - CTP=yes WERROR=yes J=4 #J>4 triggers an internal compiler in travis' g++
  - CTP=yes WALL=yes J=4

before_script:
  - rm -vrf * .git
  - wget https://raw.githubusercontent.com/votca/buildutil/master/build.sh && chmod 755 build.sh
  - if [[ $TEST = *cma* ]]; then wget http://www.lri.fr/~hansen/cma.py; fi #we set PYTHONPATH="$PWD" below

script:
  - PYTHONPATH="$PWD" ./build.sh -Wdu --prefix $PWD ${MAN:+--devdoc}
    ${TEST:+--runtest=$TEST} ${WERROR:+--warn-to-errors} ${MINIMAL:+--minimal}
    ${J:+-j$J} ${BDIR:+--builddir=$BDIR} ${NINJA:+--ninja} ${WALL:+--Wall}
    tools ${GROMACS:+gromacs} csg csgapps ${MAN:+csg-manual} ${TEST:+csg-tutorials}
    ${CTP:+kmc moo ctp}

compiler:
  - clang
  - gcc
